name: formatos_brasileiros
repository: https://github.com/asakeron/formatos_brasileiros.git
homepage: https://github.com/asakeron/formatos_brasileiros
description: |
  Collection of data types and utility functions for parsing, validating,
  generating and formating known Brazilian string encoded information
version: 0.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
